[2025-07-01 17:33:23,682: INFO: main: Welcome to my custom log]
[2025-07-01 17:49:39,295: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-07-01 17:59:30,814: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-07-01 17:59:37,487: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-07-01 17:59:54,990: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-07-01 18:02:53,914: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-07-01 18:02:58,245: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-07-01 18:04:28,823: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-07-01 18:06:27,666: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-07-01 18:06:31,822: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-07-01 18:07:45,840: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-07-01 18:07:52,375: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-07-01 18:09:55,919: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-07-01 18:10:55,768: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-07-01 19:33:29,123: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-07-01 19:40:28,892: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-07-01 19:49:51,360: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-07-01 19:49:57,065: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-07-01 19:52:57,387: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-07-01 19:53:02,297: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-07-01 19:57:15,479: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-07-01 20:00:23,595: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-07-01 20:00:23,635: INFO: common: yaml file: params.yaml loaded successfully]
[2025-07-01 20:00:23,635: INFO: common: created directory at: artifacts]
[2025-07-01 20:00:23,635: INFO: common: created directory at: artifacts/data_ingestion]
[2025-07-01 20:00:27,515: INFO: 4037744573: artifacts/data_ingestion/data.zip download! with following info: 
Connection: close
Content-Length: 11616915
Cache-Control: max-age=300
Content-Security-Policy: default-src 'none'; style-src 'unsafe-inline'; sandbox
Content-Type: application/zip
ETag: "adf745abc03891fe493c3be264ec012691fe3fa21d861f35a27edbe6d86a76b1"
Strict-Transport-Security: max-age=31536000
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-XSS-Protection: 1; mode=block
X-GitHub-Request-Id: 2F5F:29C83C:58BD2:BE1F4:6863F100
Accept-Ranges: bytes
Date: Tue, 01 Jul 2025 14:30:25 GMT
Via: 1.1 varnish
X-Served-By: cache-del21743-DEL
X-Cache: MISS
X-Cache-Hits: 0
X-Timer: S1751380225.862984,VS0,VE897
Vary: Authorization,Accept-Encoding
Access-Control-Allow-Origin: *
Cross-Origin-Resource-Policy: cross-origin
X-Fastly-Request-ID: 164ad51913cd0616fd28ffd47f76245cf90b00b9
Expires: Tue, 01 Jul 2025 14:35:25 GMT
Source-Age: 1

]
[2025-07-03 14:59:36,229: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-07-03 14:59:36,229: ERROR: main: name 'ConfigrationManager' is not defined]
Traceback (most recent call last):
  File "C:\Users\saurabh\Desktop\test-pro\hel\main.py", line 15, in <module>
    data_ingestion.main()
  File "C:\Users\saurabh\Desktop\test-pro\hel\src\cnnClassifier\pipeline\stage_01_data_ingestion.py", line 12, in main
    config = ConfigrationManager()
            ^^^^^^^^^^^^^^^^^^^
NameError: name 'ConfigrationManager' is not defined. Did you mean: 'ConfigurationManager'?
[2025-07-03 15:00:43,283: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-07-03 15:00:43,283: ERROR: main: name 'ConfigrationManager' is not defined]
Traceback (most recent call last):
  File "C:\Users\saurabh\Desktop\test-pro\hel\main.py", line 15, in <module>
    data_ingestion.main()
  File "C:\Users\saurabh\Desktop\test-pro\hel\src\cnnClassifier\pipeline\stage_01_data_ingestion.py", line 12, in main
    config = ConfigrationManager()
            ^^^^^^^^^^^^^^^^^^^
NameError: name 'ConfigrationManager' is not defined. Did you mean: 'ConfigurationManager'?
[2025-07-03 15:00:54,593: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-07-03 15:00:54,628: INFO: common: YAML file config\config.yaml loaded successfully]
[2025-07-03 15:00:54,654: INFO: common: YAML file params.yaml loaded successfully]
[2025-07-03 15:00:54,654: INFO: common: created directory at: artifacts]
[2025-07-03 15:00:54,654: INFO: common: created directory at: artifacts/data_ingestion]
[2025-07-03 15:00:54,654: INFO: data_ingestion: File already exists of size: ~ 11345 KB]
[2025-07-03 15:00:54,992: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-07-04 11:57:10,643: INFO: common: YAML file config\config.yaml loaded successfully]
[2025-07-04 11:57:10,651: INFO: common: YAML file params.yaml loaded successfully]
[2025-07-04 11:57:10,651: INFO: common: created directory at: artifacts]
[2025-07-04 11:57:10,651: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-07-04 11:57:17,789: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-07-04 11:57:18,061: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-07-10 19:57:03,601: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-07-10 19:57:03,621: INFO: common: YAML file config\config.yaml loaded successfully]
[2025-07-10 19:57:03,645: INFO: common: YAML file params.yaml loaded successfully]
[2025-07-10 19:57:03,647: INFO: common: created directory at: artifacts]
[2025-07-10 19:57:03,647: INFO: common: created directory at: artifacts/data_ingestion]
[2025-07-10 19:57:07,283: INFO: data_ingestion: artifacts/data_ingestion/data.zip download! with following info: 
Connection: close
Content-Length: 11616915
Cache-Control: max-age=300
Content-Security-Policy: default-src 'none'; style-src 'unsafe-inline'; sandbox
Content-Type: application/zip
ETag: "adf745abc03891fe493c3be264ec012691fe3fa21d861f35a27edbe6d86a76b1"
Strict-Transport-Security: max-age=31536000
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-XSS-Protection: 1; mode=block
X-GitHub-Request-Id: EFF5:39234B:7F7E:12BB9:686FCDB4
Accept-Ranges: bytes
Date: Thu, 10 Jul 2025 14:27:06 GMT
Via: 1.1 varnish
X-Served-By: cache-del21724-DEL
X-Cache: MISS
X-Cache-Hits: 0
X-Timer: S1752157625.352817,VS0,VE847
Vary: Authorization,Accept-Encoding
Access-Control-Allow-Origin: *
Cross-Origin-Resource-Policy: cross-origin
X-Fastly-Request-ID: 3e469c97da41ce9a023301d62011950864518c95
Expires: Thu, 10 Jul 2025 14:32:06 GMT
Source-Age: 1

]
[2025-07-10 19:57:07,638: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-07-10 19:57:07,638: INFO: main: *******************]
[2025-07-10 19:57:07,638: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2025-07-10 19:57:07,641: INFO: common: YAML file config\config.yaml loaded successfully]
[2025-07-10 19:57:07,641: INFO: common: YAML file params.yaml loaded successfully]
[2025-07-10 19:57:07,641: INFO: common: created directory at: artifacts]
[2025-07-10 19:57:07,646: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-07-10 19:57:08,511: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-07-10 19:57:08,712: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-07-10 19:57:08,961: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2025-07-10 20:01:58,994: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-07-10 20:01:59,002: INFO: common: YAML file config\config.yaml loaded successfully]
[2025-07-10 20:01:59,006: INFO: common: YAML file params.yaml loaded successfully]
[2025-07-10 20:01:59,007: INFO: common: created directory at: artifacts]
[2025-07-10 20:01:59,008: INFO: common: created directory at: artifacts/data_ingestion]
[2025-07-10 20:01:59,009: INFO: data_ingestion: File already exists of size: ~ 11345 KB]
[2025-07-10 20:01:59,349: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-07-10 20:01:59,349: INFO: main: *******************]
[2025-07-10 20:01:59,349: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2025-07-10 20:01:59,349: INFO: common: YAML file config\config.yaml loaded successfully]
[2025-07-10 20:01:59,349: INFO: common: YAML file params.yaml loaded successfully]
[2025-07-10 20:01:59,349: INFO: common: created directory at: artifacts]
[2025-07-10 20:01:59,365: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-07-10 20:01:59,762: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-07-10 20:01:59,978: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-07-10 20:02:00,121: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2025-07-11 16:33:04,172: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-07-11 16:33:04,193: INFO: common: YAML file config\config.yaml loaded successfully]
[2025-07-11 16:33:04,225: INFO: common: YAML file params.yaml loaded successfully]
[2025-07-11 16:33:04,229: INFO: common: created directory at: artifacts]
[2025-07-11 16:33:04,231: INFO: common: created directory at: artifacts/data_ingestion]
[2025-07-11 16:33:04,232: INFO: data_ingestion: File already exists of size: ~ 11345 KB]
[2025-07-11 16:33:05,173: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-07-11 16:33:05,175: INFO: main: *******************]
[2025-07-11 16:33:05,177: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2025-07-11 16:33:05,191: INFO: common: YAML file config\config.yaml loaded successfully]
[2025-07-11 16:33:05,223: INFO: common: YAML file params.yaml loaded successfully]
[2025-07-11 16:33:05,230: INFO: common: created directory at: artifacts]
[2025-07-11 16:33:05,233: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-07-11 16:33:08,232: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-07-11 16:33:09,194: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-07-11 16:33:10,350: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2025-07-11 19:01:20,050: INFO: common: YAML file config\config.yaml loaded successfully]
[2025-07-11 19:01:20,060: INFO: common: YAML file params.yaml loaded successfully]
[2025-07-11 19:01:20,067: INFO: common: created directory at: artifacts]
[2025-07-11 19:01:20,067: INFO: common: created directory at: artifacts\prepare_callbacks\checkpoint_dir]
[2025-07-11 19:01:20,073: INFO: common: created directory at: artifacts\prepare_callbacks\tensorboard_log_dir]
[2025-07-14 17:54:32,657: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-07-14 17:54:32,676: INFO: common: YAML file config\config.yaml loaded successfully]
[2025-07-14 17:54:32,695: INFO: common: YAML file params.yaml loaded successfully]
[2025-07-14 17:54:32,696: INFO: common: created directory at: artifacts]
[2025-07-14 17:54:32,696: INFO: common: created directory at: artifacts/data_ingestion]
[2025-07-14 17:54:32,698: INFO: data_ingestion: File already exists of size: ~ 11345 KB]
[2025-07-14 17:54:33,521: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-07-14 17:54:33,521: INFO: main: *******************]
[2025-07-14 17:54:33,522: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2025-07-14 17:54:33,526: INFO: common: YAML file config\config.yaml loaded successfully]
[2025-07-14 17:54:33,530: INFO: common: YAML file params.yaml loaded successfully]
[2025-07-14 17:54:33,532: INFO: common: created directory at: artifacts]
[2025-07-14 17:54:33,533: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-07-14 17:54:36,179: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-07-14 17:54:37,990: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-07-14 17:54:38,379: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2025-07-23 17:49:55,176: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-07-23 17:49:55,193: INFO: common: YAML file config\config.yaml loaded successfully]
[2025-07-23 17:49:55,196: INFO: common: YAML file params.yaml loaded successfully]
[2025-07-23 17:49:55,197: INFO: common: created directory at: artifacts]
[2025-07-23 17:49:55,198: INFO: common: created directory at: artifacts/data_ingestion]
[2025-07-23 17:49:55,199: INFO: data_ingestion: File already exists of size: ~ 11345 KB]
[2025-07-23 17:49:55,830: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-07-23 17:49:55,832: INFO: main: *******************]
[2025-07-23 17:49:55,832: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2025-07-23 17:49:55,841: INFO: common: YAML file config\config.yaml loaded successfully]
[2025-07-23 17:49:55,845: INFO: common: YAML file params.yaml loaded successfully]
[2025-07-23 17:49:55,850: INFO: common: created directory at: artifacts]
[2025-07-23 17:49:55,852: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-07-23 17:49:56,767: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-07-23 17:49:57,291: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-07-23 17:49:57,541: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2025-07-25 19:12:40,784: INFO: common: YAML file config\config.yaml loaded successfully]
[2025-07-25 19:12:40,794: INFO: common: YAML file params.yaml loaded successfully]
[2025-07-25 19:12:40,794: INFO: common: created directory at: artifacts]
[2025-07-25 19:12:40,794: INFO: common: created directory at: artifacts\prepare_callbacks\checkpoint_dir]
[2025-07-25 19:12:40,794: INFO: common: created directory at: artifacts\prepare_callbacks\tensorboard_log_dir]
[2025-07-25 19:24:02,167: INFO: common: YAML file config\config.yaml loaded successfully]
[2025-07-25 19:24:02,181: INFO: common: YAML file params.yaml loaded successfully]
[2025-07-25 19:24:02,187: INFO: common: created directory at: artifacts]
[2025-07-25 19:24:02,190: INFO: common: created directory at: artifacts\prepare_callbacks\checkpoint_dir]
[2025-07-25 19:24:02,193: INFO: common: created directory at: artifacts\prepare_callbacks\tensorboard_log_dir]
[2025-07-25 19:24:02,197: INFO: common: created directory at: artifacts\training]
[2025-07-25 19:24:03,145: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-07-25 19:27:19,705: INFO: common: YAML file config\config.yaml loaded successfully]
[2025-07-25 19:27:19,705: INFO: common: YAML file params.yaml loaded successfully]
[2025-07-25 19:27:19,711: INFO: common: created directory at: artifacts]
[2025-07-25 19:27:19,713: INFO: common: created directory at: artifacts\prepare_callbacks\checkpoint_dir]
[2025-07-25 19:27:19,715: INFO: common: created directory at: artifacts\prepare_callbacks\tensorboard_log_dir]
[2025-07-25 19:27:19,724: INFO: common: created directory at: artifacts\training]
[2025-07-25 19:31:55,800: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-07-25 19:31:56,163: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-07-26 09:44:04,092: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-07-26 09:44:04,107: INFO: common: YAML file config\config.yaml loaded successfully]
[2025-07-26 09:44:04,131: INFO: common: YAML file params.yaml loaded successfully]
[2025-07-26 09:44:04,132: INFO: common: created directory at: artifacts]
[2025-07-26 09:44:04,133: INFO: common: created directory at: artifacts/data_ingestion]
[2025-07-26 09:44:04,137: INFO: data_ingestion: File already exists of size: ~ 11345 KB]
[2025-07-26 09:44:04,663: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-07-26 09:44:04,663: INFO: main: *******************]
[2025-07-26 09:44:04,663: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2025-07-26 09:44:04,663: INFO: common: YAML file config\config.yaml loaded successfully]
[2025-07-26 09:44:04,663: INFO: common: YAML file params.yaml loaded successfully]
[2025-07-26 09:44:04,663: INFO: common: created directory at: artifacts]
[2025-07-26 09:44:04,663: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-07-26 09:44:05,397: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-07-26 09:44:05,754: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-07-26 09:44:06,026: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2025-07-26 09:44:06,026: INFO: main: *******************]
[2025-07-26 09:44:06,027: INFO: main: >>>>>> stage Training started <<<<<<]
[2025-07-26 09:44:06,033: INFO: common: YAML file config\config.yaml loaded successfully]
[2025-07-26 09:44:06,037: INFO: common: YAML file params.yaml loaded successfully]
[2025-07-26 09:44:06,038: INFO: common: created directory at: artifacts]
[2025-07-26 09:44:06,039: INFO: common: created directory at: artifacts\prepare_callbacks\checkpoint_dir]
[2025-07-26 09:44:06,039: INFO: common: created directory at: artifacts\prepare_callbacks\tensorboard_log_dir]
[2025-07-26 09:44:06,039: INFO: common: created directory at: artifacts\training]
[2025-07-26 09:44:06,334: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-07-26 09:44:10,369: ERROR: main: numpy() is only available when eager execution is enabled.]
Traceback (most recent call last):
  File "C:\Users\saurabh\Desktop\test-pro\hel\main.py", line 38, in <module>
    model_trainer.main()
  File "C:\Users\saurabh\Desktop\test-pro\hel\src\cnnClassifier\pipeline\stage_03_training.py", line 25, in main
    training.train(
  File "C:\Users\saurabh\Desktop\test-pro\hel\src\cnnClassifier\components\training.py", line 68, in train
    self.model.fit(
  File "C:\Users\saurabh\Desktop\test-pro\hel\.venv\Lib\site-packages\keras\src\utils\traceback_utils.py", line 122, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Users\saurabh\Desktop\test-pro\hel\.venv\Lib\site-packages\keras\src\backend\tensorflow\core.py", line 171, in convert_to_numpy
    return np.array(x)
           ^^^^^^^^^^^
NotImplementedError: numpy() is only available when eager execution is enabled.
[2025-07-26 09:51:40,494: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-07-26 09:51:40,495: INFO: common: YAML file config\config.yaml loaded successfully]
[2025-07-26 09:51:40,495: INFO: common: YAML file params.yaml loaded successfully]
[2025-07-26 09:51:40,495: INFO: common: created directory at: artifacts]
[2025-07-26 09:51:40,495: INFO: common: created directory at: artifacts/data_ingestion]
[2025-07-26 09:51:40,495: INFO: data_ingestion: File already exists of size: ~ 11345 KB]
[2025-07-26 09:51:40,830: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-07-26 09:51:40,830: INFO: main: *******************]
[2025-07-26 09:51:40,830: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2025-07-26 09:51:40,830: INFO: common: YAML file config\config.yaml loaded successfully]
[2025-07-26 09:51:40,830: INFO: common: YAML file params.yaml loaded successfully]
[2025-07-26 09:51:40,830: INFO: common: created directory at: artifacts]
[2025-07-26 09:51:40,830: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-07-26 09:51:41,599: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-07-26 09:51:42,497: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-07-26 09:51:42,813: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2025-07-26 09:51:42,829: INFO: main: *******************]
[2025-07-26 09:51:42,829: INFO: main: >>>>>> stage Training started <<<<<<]
[2025-07-26 09:51:42,829: INFO: common: YAML file config\config.yaml loaded successfully]
[2025-07-26 09:51:42,843: INFO: common: YAML file params.yaml loaded successfully]
[2025-07-26 09:51:42,845: INFO: common: created directory at: artifacts]
[2025-07-26 09:51:42,847: INFO: common: created directory at: artifacts\prepare_callbacks\checkpoint_dir]
[2025-07-26 09:51:42,848: INFO: common: created directory at: artifacts\prepare_callbacks\tensorboard_log_dir]
[2025-07-26 09:51:42,849: INFO: common: created directory at: artifacts\training]
[2025-07-26 09:51:43,572: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-07-26 09:52:02,283: ERROR: main: Unknown variable: <Variable path=dense/kernel, shape=(25088, 2), dtype=float32, value=[[ 0.00327441 -0.01121099]
 [-0.00674632 -0.01132364]
 [-0.0132332   0.00981108]
 ...
 [-0.00244577  0.01262251]
 [ 0.00880086  0.00535013]
 [-0.0129352   0.00959326]]>. This optimizer can only be called for the variables it was originally built with. When working with a new set of variables, you should recreate a new optimizer instance.]
Traceback (most recent call last):
  File "C:\Users\saurabh\Desktop\test-pro\hel\main.py", line 38, in <module>
    model_trainer.main()
  File "C:\Users\saurabh\Desktop\test-pro\hel\src\cnnClassifier\pipeline\stage_03_training.py", line 25, in main
    training.train(
  File "C:\Users\saurabh\Desktop\test-pro\hel\src\cnnClassifier\components\training.py", line 68, in train
    self.model.fit(
  File "C:\Users\saurabh\Desktop\test-pro\hel\.venv\Lib\site-packages\keras\src\utils\traceback_utils.py", line 122, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Users\saurabh\Desktop\test-pro\hel\.venv\Lib\site-packages\keras\src\optimizers\base_optimizer.py", line 409, in _check_variables_are_known
    raise ValueError(
ValueError: Unknown variable: <Variable path=dense/kernel, shape=(25088, 2), dtype=float32, value=[[ 0.00327441 -0.01121099]
 [-0.00674632 -0.01132364]
 [-0.0132332   0.00981108]
 ...
 [-0.00244577  0.01262251]
 [ 0.00880086  0.00535013]
 [-0.0129352   0.00959326]]>. This optimizer can only be called for the variables it was originally built with. When working with a new set of variables, you should recreate a new optimizer instance.
[2025-07-26 09:54:36,991: INFO: main: >>>>>> Data Ingestion Stage started <<<<<<]
[2025-07-26 09:54:36,991: INFO: common: YAML file config\config.yaml loaded successfully]
[2025-07-26 09:54:36,991: INFO: common: YAML file params.yaml loaded successfully]
[2025-07-26 09:54:36,991: INFO: common: created directory at: artifacts]
[2025-07-26 09:54:36,991: INFO: common: created directory at: artifacts/data_ingestion]
[2025-07-26 09:54:36,991: INFO: data_ingestion: File already exists of size: ~ 11345 KB]
[2025-07-26 09:54:37,422: INFO: main: >>>>>> Data Ingestion Stage completed <<<<<<

x==========x]
[2025-07-26 09:54:37,423: INFO: main: >>>>>> Prepare Base Model started <<<<<<]
[2025-07-26 09:54:37,425: INFO: common: YAML file config\config.yaml loaded successfully]
[2025-07-26 09:54:37,430: INFO: common: YAML file params.yaml loaded successfully]
[2025-07-26 09:54:37,431: INFO: common: created directory at: artifacts]
[2025-07-26 09:54:37,431: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-07-26 09:54:37,880: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-07-26 09:54:38,078: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-07-26 09:54:38,232: INFO: main: >>>>>> Prepare Base Model completed <<<<<<

x==========x]
[2025-07-26 09:54:38,232: INFO: main: >>>>>> Training started <<<<<<]
[2025-07-26 09:54:38,232: INFO: common: YAML file config\config.yaml loaded successfully]
[2025-07-26 09:54:38,247: INFO: common: YAML file params.yaml loaded successfully]
[2025-07-26 09:54:38,250: INFO: common: created directory at: artifacts]
[2025-07-26 09:54:38,252: INFO: common: created directory at: artifacts\prepare_callbacks\checkpoint_dir]
[2025-07-26 09:54:38,252: INFO: common: created directory at: artifacts\prepare_callbacks\tensorboard_log_dir]
[2025-07-26 09:54:38,255: INFO: common: created directory at: artifacts\training]
[2025-07-26 09:54:38,618: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-07-26 09:54:53,578: ERROR: main: Unknown variable: <Variable path=dense/kernel, shape=(25088, 2), dtype=float32, value=[[-0.00512377  0.00173294]
 [ 0.01217184  0.00256376]
 [ 0.01001306 -0.00013334]
 ...
 [-0.01115712  0.00596896]
 [-0.0063059   0.00596262]
 [-0.00651224  0.01451804]]>. This optimizer can only be called for the variables it was originally built with. When working with a new set of variables, you should recreate a new optimizer instance.]
Traceback (most recent call last):
  File "C:\Users\saurabh\Desktop\test-pro\hel\main.py", line 78, in <module>
    model_trainer.main()
  File "C:\Users\saurabh\Desktop\test-pro\hel\src\cnnClassifier\pipeline\stage_03_training.py", line 25, in main
    training.train(
  File "C:\Users\saurabh\Desktop\test-pro\hel\src\cnnClassifier\components\training.py", line 68, in train
    self.model.fit(
  File "C:\Users\saurabh\Desktop\test-pro\hel\.venv\Lib\site-packages\keras\src\utils\traceback_utils.py", line 122, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Users\saurabh\Desktop\test-pro\hel\.venv\Lib\site-packages\keras\src\optimizers\base_optimizer.py", line 409, in _check_variables_are_known
    raise ValueError(
ValueError: Unknown variable: <Variable path=dense/kernel, shape=(25088, 2), dtype=float32, value=[[-0.00512377  0.00173294]
 [ 0.01217184  0.00256376]
 [ 0.01001306 -0.00013334]
 ...
 [-0.01115712  0.00596896]
 [-0.0063059   0.00596262]
 [-0.00651224  0.01451804]]>. This optimizer can only be called for the variables it was originally built with. When working with a new set of variables, you should recreate a new optimizer instance.
[2025-07-30 11:56:16,941: INFO: main: >>>>>> Data Ingestion Stage started <<<<<<]
[2025-07-30 11:56:16,955: INFO: common: YAML file config\config.yaml loaded successfully]
[2025-07-30 11:56:16,974: INFO: common: YAML file params.yaml loaded successfully]
[2025-07-30 11:56:16,974: INFO: common: created directory at: artifacts]
[2025-07-30 11:56:16,974: INFO: common: created directory at: artifacts/data_ingestion]
[2025-07-30 11:56:16,974: INFO: data_ingestion: File already exists of size: ~ 11345 KB]
[2025-07-30 11:56:17,504: INFO: main: >>>>>> Data Ingestion Stage completed <<<<<<

x==========x]
[2025-07-30 11:56:17,504: INFO: main: >>>>>> Prepare Base Model started <<<<<<]
[2025-07-30 11:56:17,504: INFO: common: YAML file config\config.yaml loaded successfully]
[2025-07-30 11:56:17,509: INFO: common: YAML file params.yaml loaded successfully]
[2025-07-30 11:56:17,509: INFO: common: created directory at: artifacts]
[2025-07-30 11:56:17,509: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-07-30 11:56:18,249: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-07-30 11:56:18,624: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-07-30 11:56:18,924: INFO: main: >>>>>> Prepare Base Model completed <<<<<<

x==========x]
[2025-07-30 11:56:18,924: INFO: main: >>>>>> Training started <<<<<<]
[2025-07-30 11:56:18,931: INFO: common: YAML file config\config.yaml loaded successfully]
[2025-07-30 11:56:18,936: INFO: common: YAML file params.yaml loaded successfully]
[2025-07-30 11:56:18,937: INFO: common: created directory at: artifacts]
[2025-07-30 11:56:18,937: INFO: common: created directory at: artifacts\prepare_callbacks\checkpoint_dir]
[2025-07-30 11:56:18,939: INFO: common: created directory at: artifacts\prepare_callbacks\tensorboard_log_dir]
[2025-07-30 11:56:18,939: INFO: common: created directory at: artifacts\training]
[2025-07-30 11:56:19,289: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-07-30 11:56:39,699: ERROR: main: Unknown variable: <Variable path=dense/kernel, shape=(25088, 2), dtype=float32, value=[[ 0.00449354 -0.00716807]
 [-0.00200314  0.0007564 ]
 [ 0.00173209 -0.00626168]
 ...
 [-0.0082608   0.0091464 ]
 [-0.00626778 -0.01010078]
 [ 0.01380776  0.00070208]]>. This optimizer can only be called for the variables it was originally built with. When working with a new set of variables, you should recreate a new optimizer instance.]
Traceback (most recent call last):
  File "C:\Users\saurabh\Desktop\test-pro\hel\main.py", line 78, in <module>
    model_trainer.main()
  File "C:\Users\saurabh\Desktop\test-pro\hel\src\cnnClassifier\pipeline\stage_03_training.py", line 25, in main
    training.train(
  File "C:\Users\saurabh\Desktop\test-pro\hel\src\cnnClassifier\components\training.py", line 68, in train
    self.model.fit(
  File "C:\Users\saurabh\Desktop\test-pro\hel\.venv\Lib\site-packages\keras\src\utils\traceback_utils.py", line 122, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Users\saurabh\Desktop\test-pro\hel\.venv\Lib\site-packages\keras\src\optimizers\base_optimizer.py", line 409, in _check_variables_are_known
    raise ValueError(
ValueError: Unknown variable: <Variable path=dense/kernel, shape=(25088, 2), dtype=float32, value=[[ 0.00449354 -0.00716807]
 [-0.00200314  0.0007564 ]
 [ 0.00173209 -0.00626168]
 ...
 [-0.0082608   0.0091464 ]
 [-0.00626778 -0.01010078]
 [ 0.01380776  0.00070208]]>. This optimizer can only be called for the variables it was originally built with. When working with a new set of variables, you should recreate a new optimizer instance.
[2025-07-30 12:05:53,325: INFO: main: >>>>>> Data Ingestion Stage started <<<<<<]
[2025-07-30 12:05:53,330: INFO: common: YAML file config\config.yaml loaded successfully]
[2025-07-30 12:05:53,334: INFO: common: YAML file params.yaml loaded successfully]
[2025-07-30 12:05:53,334: INFO: common: created directory at: artifacts]
[2025-07-30 12:05:53,334: INFO: common: created directory at: artifacts/data_ingestion]
[2025-07-30 12:05:53,337: INFO: data_ingestion: File already exists of size: ~ 11345 KB]
[2025-07-30 12:05:53,754: INFO: main: >>>>>> Data Ingestion Stage completed <<<<<<

x==========x]
[2025-07-30 12:05:53,754: INFO: main: >>>>>> Prepare Base Model started <<<<<<]
[2025-07-30 12:05:53,754: INFO: common: YAML file config\config.yaml loaded successfully]
[2025-07-30 12:05:53,754: INFO: common: YAML file params.yaml loaded successfully]
[2025-07-30 12:05:53,754: INFO: common: created directory at: artifacts]
[2025-07-30 12:05:53,762: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-07-30 12:05:54,269: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-07-30 12:05:54,497: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-07-30 12:05:54,689: INFO: main: >>>>>> Prepare Base Model completed <<<<<<

x==========x]
[2025-07-30 12:05:54,689: INFO: main: >>>>>> Training started <<<<<<]
[2025-07-30 12:05:54,689: INFO: common: YAML file config\config.yaml loaded successfully]
[2025-07-30 12:05:54,709: INFO: common: YAML file params.yaml loaded successfully]
[2025-07-30 12:05:54,710: INFO: common: created directory at: artifacts]
[2025-07-30 12:05:54,712: INFO: common: created directory at: artifacts\prepare_callbacks\checkpoint_dir]
[2025-07-30 12:05:54,713: INFO: common: created directory at: artifacts\prepare_callbacks\tensorboard_log_dir]
[2025-07-30 12:05:54,714: INFO: common: created directory at: artifacts\training]
[2025-07-30 12:05:55,113: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-07-30 12:05:55,120: ERROR: main: 'TrainingConfig' object has no attribute 'params_learning_rate']
Traceback (most recent call last):
  File "C:\Users\saurabh\Desktop\test-pro\hel\main.py", line 78, in <module>
    model_trainer.main()
  File "C:\Users\saurabh\Desktop\test-pro\hel\src\cnnClassifier\pipeline\stage_03_training.py", line 23, in main
    training.get_base_model()
  File "C:\Users\saurabh\Desktop\test-pro\hel\src\cnnClassifier\components\training.py", line 21, in get_base_model
    optimizer=tf.keras.optimizers.Adam(learning_rate=self.config.params_learning_rate),
                                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'TrainingConfig' object has no attribute 'params_learning_rate'
[2025-07-30 12:10:18,797: INFO: main: >>>>>> Data Ingestion Stage started <<<<<<]
[2025-07-30 12:10:18,801: INFO: common: YAML file config\config.yaml loaded successfully]
[2025-07-30 12:10:18,801: INFO: common: YAML file params.yaml loaded successfully]
[2025-07-30 12:10:18,801: INFO: common: created directory at: artifacts]
[2025-07-30 12:10:18,801: INFO: common: created directory at: artifacts/data_ingestion]
[2025-07-30 12:10:18,801: INFO: data_ingestion: File already exists of size: ~ 11345 KB]
[2025-07-30 12:10:19,132: INFO: main: >>>>>> Data Ingestion Stage completed <<<<<<

x==========x]
[2025-07-30 12:10:19,132: INFO: main: >>>>>> Prepare Base Model started <<<<<<]
[2025-07-30 12:10:19,134: INFO: common: YAML file config\config.yaml loaded successfully]
[2025-07-30 12:10:19,134: INFO: common: YAML file params.yaml loaded successfully]
[2025-07-30 12:10:19,134: INFO: common: created directory at: artifacts]
[2025-07-30 12:10:19,139: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-07-30 12:10:19,610: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-07-30 12:10:19,843: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-07-30 12:10:19,996: INFO: main: >>>>>> Prepare Base Model completed <<<<<<

x==========x]
[2025-07-30 12:10:19,996: INFO: main: >>>>>> Training started <<<<<<]
[2025-07-30 12:10:20,012: INFO: common: YAML file config\config.yaml loaded successfully]
[2025-07-30 12:10:20,017: INFO: common: YAML file params.yaml loaded successfully]
[2025-07-30 12:10:20,018: INFO: common: created directory at: artifacts]
[2025-07-30 12:10:20,018: INFO: common: created directory at: artifacts\prepare_callbacks\checkpoint_dir]
[2025-07-30 12:10:20,018: INFO: common: created directory at: artifacts\prepare_callbacks\tensorboard_log_dir]
[2025-07-30 12:10:20,018: INFO: common: created directory at: artifacts\training]
[2025-07-30 12:10:20,408: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-07-30 12:10:32,651: ERROR: main: Unknown variable: <Variable path=dense/kernel, shape=(25088, 2), dtype=float32, value=[[-0.00585569  0.01254263]
 [ 0.01363016 -0.0104808 ]
 [-0.00032481 -0.00085794]
 ...
 [-0.00611418  0.01097947]
 [ 0.00254515  0.00788366]
 [ 0.00264257  0.0034414 ]]>. This optimizer can only be called for the variables it was originally built with. When working with a new set of variables, you should recreate a new optimizer instance.]
Traceback (most recent call last):
  File "C:\Users\saurabh\Desktop\test-pro\hel\main.py", line 78, in <module>
    model_trainer.main()
  File "C:\Users\saurabh\Desktop\test-pro\hel\src\cnnClassifier\pipeline\stage_03_training.py", line 25, in main
    training.train(
  File "C:\Users\saurabh\Desktop\test-pro\hel\src\cnnClassifier\components\training.py", line 166, in train
    self.model.fit(
  File "C:\Users\saurabh\Desktop\test-pro\hel\.venv\Lib\site-packages\keras\src\utils\traceback_utils.py", line 122, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Users\saurabh\Desktop\test-pro\hel\.venv\Lib\site-packages\keras\src\optimizers\base_optimizer.py", line 409, in _check_variables_are_known
    raise ValueError(
ValueError: Unknown variable: <Variable path=dense/kernel, shape=(25088, 2), dtype=float32, value=[[-0.00585569  0.01254263]
 [ 0.01363016 -0.0104808 ]
 [-0.00032481 -0.00085794]
 ...
 [-0.00611418  0.01097947]
 [ 0.00254515  0.00788366]
 [ 0.00264257  0.0034414 ]]>. This optimizer can only be called for the variables it was originally built with. When working with a new set of variables, you should recreate a new optimizer instance.
[2025-07-30 12:22:49,034: INFO: main: >>>>>> Data Ingestion Stage started <<<<<<]
[2025-07-30 12:22:49,034: INFO: common: YAML file config\config.yaml loaded successfully]
[2025-07-30 12:22:49,034: INFO: common: YAML file params.yaml loaded successfully]
[2025-07-30 12:22:49,034: INFO: common: created directory at: artifacts]
[2025-07-30 12:22:49,049: INFO: common: created directory at: artifacts/data_ingestion]
[2025-07-30 12:22:49,049: INFO: data_ingestion: File already exists of size: ~ 11345 KB]
[2025-07-30 12:22:49,421: INFO: main: >>>>>> Data Ingestion Stage completed <<<<<<

x==========x]
[2025-07-30 12:22:49,421: INFO: main: >>>>>> Prepare Base Model started <<<<<<]
[2025-07-30 12:22:49,437: INFO: common: YAML file config\config.yaml loaded successfully]
[2025-07-30 12:22:49,437: INFO: common: YAML file params.yaml loaded successfully]
[2025-07-30 12:22:49,437: INFO: common: created directory at: artifacts]
[2025-07-30 12:22:49,443: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-07-30 12:22:49,954: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-07-30 12:22:50,144: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-07-30 12:22:50,324: INFO: main: >>>>>> Prepare Base Model completed <<<<<<

x==========x]
[2025-07-30 12:22:50,324: INFO: main: >>>>>> Training started <<<<<<]
[2025-07-30 12:22:50,338: INFO: common: YAML file config\config.yaml loaded successfully]
[2025-07-30 12:22:50,338: INFO: common: YAML file params.yaml loaded successfully]
[2025-07-30 12:22:50,338: INFO: common: created directory at: artifacts]
[2025-07-30 12:22:50,344: INFO: common: created directory at: artifacts\prepare_callbacks\checkpoint_dir]
[2025-07-30 12:22:50,345: INFO: common: created directory at: artifacts\prepare_callbacks\tensorboard_log_dir]
[2025-07-30 12:22:50,345: INFO: common: created directory at: artifacts\training]
[2025-07-30 12:22:50,820: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-07-30 12:23:02,964: ERROR: main: Unknown variable: <Variable path=dense/kernel, shape=(25088, 2), dtype=float32, value=[[-0.0017892  -0.01317776]
 [-0.00670916 -0.00520753]
 [-0.0045951  -0.00164909]
 ...
 [ 0.00448495 -0.00242305]
 [ 0.01364453  0.01463016]
 [ 0.00423807 -0.00103413]]>. This optimizer can only be called for the variables it was originally built with. When working with a new set of variables, you should recreate a new optimizer instance.]
Traceback (most recent call last):
  File "C:\Users\saurabh\Desktop\test-pro\hel\main.py", line 78, in <module>
    model_trainer.main()
  File "C:\Users\saurabh\Desktop\test-pro\hel\src\cnnClassifier\pipeline\stage_03_training.py", line 25, in main
    training.train(
  File "C:\Users\saurabh\Desktop\test-pro\hel\src\cnnClassifier\components\training.py", line 166, in train
    self.model.fit(
  File "C:\Users\saurabh\Desktop\test-pro\hel\.venv\Lib\site-packages\keras\src\utils\traceback_utils.py", line 122, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Users\saurabh\Desktop\test-pro\hel\.venv\Lib\site-packages\keras\src\optimizers\base_optimizer.py", line 409, in _check_variables_are_known
    raise ValueError(
ValueError: Unknown variable: <Variable path=dense/kernel, shape=(25088, 2), dtype=float32, value=[[-0.0017892  -0.01317776]
 [-0.00670916 -0.00520753]
 [-0.0045951  -0.00164909]
 ...
 [ 0.00448495 -0.00242305]
 [ 0.01364453  0.01463016]
 [ 0.00423807 -0.00103413]]>. This optimizer can only be called for the variables it was originally built with. When working with a new set of variables, you should recreate a new optimizer instance.
[2025-07-30 12:25:45,636: INFO: main: >>>>>> Data Ingestion Stage started <<<<<<]
[2025-07-30 12:25:45,636: INFO: common: YAML file config\config.yaml loaded successfully]
[2025-07-30 12:25:45,636: INFO: common: YAML file params.yaml loaded successfully]
[2025-07-30 12:25:45,636: INFO: common: created directory at: artifacts]
[2025-07-30 12:25:45,636: INFO: common: created directory at: artifacts/data_ingestion]
[2025-07-30 12:25:45,636: INFO: data_ingestion: File already exists of size: ~ 11345 KB]
[2025-07-30 12:25:46,052: INFO: main: >>>>>> Data Ingestion Stage completed <<<<<<

x==========x]
[2025-07-30 12:25:46,052: INFO: main: >>>>>> Prepare Base Model started <<<<<<]
[2025-07-30 12:25:46,052: INFO: common: YAML file config\config.yaml loaded successfully]
[2025-07-30 12:25:46,059: INFO: common: YAML file params.yaml loaded successfully]
[2025-07-30 12:25:46,059: INFO: common: created directory at: artifacts]
[2025-07-30 12:25:46,061: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-07-30 12:25:46,492: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-07-30 12:25:46,725: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-07-30 12:25:46,967: INFO: main: >>>>>> Prepare Base Model completed <<<<<<

x==========x]
[2025-07-30 12:25:46,968: INFO: main: >>>>>> Training started <<<<<<]
[2025-07-30 12:25:46,978: INFO: common: YAML file config\config.yaml loaded successfully]
[2025-07-30 12:25:46,982: INFO: common: YAML file params.yaml loaded successfully]
[2025-07-30 12:25:46,993: INFO: common: created directory at: artifacts]
[2025-07-30 12:25:46,997: INFO: common: created directory at: artifacts\prepare_callbacks\checkpoint_dir]
[2025-07-30 12:25:47,005: INFO: common: created directory at: artifacts\prepare_callbacks\tensorboard_log_dir]
[2025-07-30 12:25:47,010: INFO: common: created directory at: artifacts\training]
[2025-07-30 12:25:47,338: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-07-30 12:25:47,338: ERROR: main: 'TrainingConfig' object has no attribute 'params_learning_rate']
Traceback (most recent call last):
  File "C:\Users\saurabh\Desktop\test-pro\hel\main.py", line 78, in <module>
    model_trainer.main()
  File "C:\Users\saurabh\Desktop\test-pro\hel\src\cnnClassifier\pipeline\stage_03_training.py", line 23, in main
    training.get_base_model()
  File "C:\Users\saurabh\Desktop\test-pro\hel\src\cnnClassifier\components\training.py", line 21, in get_base_model
    optimizer=Adam(learning_rate=self.config.params_learning_rate),
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'TrainingConfig' object has no attribute 'params_learning_rate'
[2025-07-30 12:29:12,575: INFO: main: >>>>>> Data Ingestion Stage started <<<<<<]
[2025-07-30 12:29:12,577: INFO: common: YAML file config\config.yaml loaded successfully]
[2025-07-30 12:29:12,577: INFO: common: YAML file params.yaml loaded successfully]
[2025-07-30 12:29:12,577: INFO: common: created directory at: artifacts]
[2025-07-30 12:29:12,577: INFO: common: created directory at: artifacts/data_ingestion]
[2025-07-30 12:29:12,577: INFO: data_ingestion: File already exists of size: ~ 11345 KB]
[2025-07-30 12:29:13,003: INFO: main: >>>>>> Data Ingestion Stage completed <<<<<<

x==========x]
[2025-07-30 12:29:13,003: INFO: main: >>>>>> Prepare Base Model started <<<<<<]
[2025-07-30 12:29:13,006: INFO: common: YAML file config\config.yaml loaded successfully]
[2025-07-30 12:29:13,008: INFO: common: YAML file params.yaml loaded successfully]
[2025-07-30 12:29:13,008: INFO: common: created directory at: artifacts]
[2025-07-30 12:29:13,009: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-07-30 12:29:13,426: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-07-30 12:29:13,647: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-07-30 12:29:13,792: INFO: main: >>>>>> Prepare Base Model completed <<<<<<

x==========x]
[2025-07-30 12:29:13,792: INFO: main: >>>>>> Training started <<<<<<]
[2025-07-30 12:29:13,796: INFO: common: YAML file config\config.yaml loaded successfully]
[2025-07-30 12:29:13,796: INFO: common: YAML file params.yaml loaded successfully]
[2025-07-30 12:29:13,796: INFO: common: created directory at: artifacts]
[2025-07-30 12:29:13,802: INFO: common: created directory at: artifacts\prepare_callbacks\checkpoint_dir]
[2025-07-30 12:29:13,802: INFO: common: created directory at: artifacts\prepare_callbacks\tensorboard_log_dir]
[2025-07-30 12:29:13,802: INFO: common: created directory at: artifacts\training]
[2025-07-30 12:29:13,802: ERROR: main: TrainingConfig.__init__() missing 1 required positional argument: 'params_learning_rate']
Traceback (most recent call last):
  File "C:\Users\saurabh\Desktop\test-pro\hel\main.py", line 78, in <module>
    model_trainer.main()
  File "C:\Users\saurabh\Desktop\test-pro\hel\src\cnnClassifier\pipeline\stage_03_training.py", line 21, in main
    training_config = config.get_training_config()
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\saurabh\Desktop\test-pro\hel\src\cnnClassifier\config\configuration.py", line 190, in get_training_config
    return TrainingConfig(
           ^^^^^^^^^^^^^^^
TypeError: TrainingConfig.__init__() missing 1 required positional argument: 'params_learning_rate'
[2025-07-30 12:33:26,747: INFO: main: >>>>>> Data Ingestion Stage started <<<<<<]
[2025-07-30 12:33:26,747: INFO: common: YAML file config\config.yaml loaded successfully]
[2025-07-30 12:33:26,747: INFO: common: YAML file params.yaml loaded successfully]
[2025-07-30 12:33:26,747: INFO: common: created directory at: artifacts]
[2025-07-30 12:33:26,747: INFO: common: created directory at: artifacts/data_ingestion]
[2025-07-30 12:33:26,747: INFO: data_ingestion: File already exists of size: ~ 11345 KB]
[2025-07-30 12:33:27,131: INFO: main: >>>>>> Data Ingestion Stage completed <<<<<<

x==========x]
[2025-07-30 12:33:27,131: INFO: main: >>>>>> Prepare Base Model started <<<<<<]
[2025-07-30 12:33:27,131: INFO: common: YAML file config\config.yaml loaded successfully]
[2025-07-30 12:33:27,131: INFO: common: YAML file params.yaml loaded successfully]
[2025-07-30 12:33:27,131: INFO: common: created directory at: artifacts]
[2025-07-30 12:33:27,131: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-07-30 12:33:27,680: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-07-30 12:33:27,892: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-07-30 12:33:28,067: INFO: main: >>>>>> Prepare Base Model completed <<<<<<

x==========x]
[2025-07-30 12:33:28,067: INFO: main: >>>>>> Training started <<<<<<]
[2025-07-30 12:33:28,067: INFO: common: YAML file config\config.yaml loaded successfully]
[2025-07-30 12:33:28,075: INFO: common: YAML file params.yaml loaded successfully]
[2025-07-30 12:33:28,076: INFO: common: created directory at: artifacts]
[2025-07-30 12:33:28,076: INFO: common: created directory at: artifacts\prepare_callbacks\checkpoint_dir]
[2025-07-30 12:33:28,076: INFO: common: created directory at: artifacts\prepare_callbacks\tensorboard_log_dir]
[2025-07-30 12:33:28,078: INFO: common: created directory at: artifacts\training]
[2025-07-30 12:33:28,326: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-07-30 12:37:03,394: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-07-30 12:37:03,562: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-07-30 12:37:03,794: INFO: main: >>>>>> Training completed <<<<<<

x==========x]
[2025-07-30 12:37:03,794: INFO: main: >>>>>> Evaluation started <<<<<<]
[2025-07-30 12:37:03,794: INFO: common: YAML file config\config.yaml loaded successfully]
[2025-07-30 12:37:03,794: INFO: common: YAML file params.yaml loaded successfully]
[2025-07-30 12:37:03,794: INFO: common: created directory at: artifacts]
[2025-07-30 12:37:04,088: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-07-30 12:37:30,557: INFO: common: json file saved at: scores.json]
[2025-07-30 12:37:30,557: INFO: main: >>>>>> Evaluation completed <<<<<<

x==========x]
[2025-07-30 13:02:33,497: INFO: stage_01_data_ingestion: >>>> stage Data Ingestion stage started >>>>>]
[2025-07-30 13:02:33,497: INFO: common: YAML file config\config.yaml loaded successfully]
[2025-07-30 13:02:33,497: INFO: common: YAML file params.yaml loaded successfully]
[2025-07-30 13:02:33,497: INFO: common: created directory at: artifacts]
[2025-07-30 13:02:33,497: INFO: common: created directory at: artifacts/data_ingestion]
[2025-07-30 13:02:33,497: INFO: data_ingestion: File already exists of size: ~ 11345 KB]
[2025-07-30 13:02:34,773: INFO: stage_01_data_ingestion: >>> stage Data Ingestion stage completed >>>>>

 x======x]
[2025-07-30 13:02:50,048: INFO: stage_02_prepare_base_model: *******************]
[2025-07-30 13:02:50,048: INFO: stage_02_prepare_base_model: >>>>>> stage Prepare base model started <<<<<<]
[2025-07-30 13:02:50,050: INFO: common: YAML file config\config.yaml loaded successfully]
[2025-07-30 13:02:50,050: INFO: common: YAML file params.yaml loaded successfully]
[2025-07-30 13:02:50,050: INFO: common: created directory at: artifacts]
[2025-07-30 13:02:50,057: INFO: common: created directory at: artifacts/prepare_base_model]
[2025-07-30 13:02:50,574: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-07-30 13:02:50,729: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-07-30 13:02:50,893: INFO: stage_02_prepare_base_model: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2025-07-30 13:02:58,692: INFO: stage_03_training: *******************]
[2025-07-30 13:02:58,692: INFO: stage_03_training: >>>>>> stage Training started <<<<<<]
[2025-07-30 13:02:58,692: INFO: common: YAML file config\config.yaml loaded successfully]
[2025-07-30 13:02:58,692: INFO: common: YAML file params.yaml loaded successfully]
[2025-07-30 13:02:58,692: INFO: common: created directory at: artifacts]
[2025-07-30 13:02:58,692: INFO: common: created directory at: artifacts\prepare_callbacks\checkpoint_dir]
[2025-07-30 13:02:58,692: INFO: common: created directory at: artifacts\prepare_callbacks\tensorboard_log_dir]
[2025-07-30 13:02:58,703: INFO: common: created directory at: artifacts\training]
[2025-07-30 13:02:59,071: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-07-30 13:06:45,414: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-07-30 13:06:45,619: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-07-30 13:06:45,773: INFO: stage_03_training: >>>>>> stage Training completed <<<<<<

x==========x]
[2025-07-30 13:06:59,457: INFO: stage_04_evaluation: *******************]
[2025-07-30 13:06:59,457: INFO: stage_04_evaluation: >>>>>> stage Evaluation stage started <<<<<<]
[2025-07-30 13:06:59,457: INFO: common: YAML file config\config.yaml loaded successfully]
[2025-07-30 13:06:59,457: INFO: common: YAML file params.yaml loaded successfully]
[2025-07-30 13:06:59,457: INFO: common: created directory at: artifacts]
[2025-07-30 13:06:59,832: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-07-30 13:07:25,422: INFO: common: json file saved at: scores.json]
[2025-07-30 13:07:25,422: INFO: stage_04_evaluation: >>>>>> stage Evaluation stage completed <<<<<<

x==========x]
[2025-08-01 10:26:01,823: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.1.38:8080]
[2025-08-01 10:26:01,823: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2025-08-01 10:26:14,633: INFO: _internal: 127.0.0.1 - - [01/Aug/2025 10:26:14] "GET / HTTP/1.1" 200 -]
[2025-08-01 10:28:00,222: INFO: _internal: 127.0.0.1 - - [01/Aug/2025 10:28:00] "GET / HTTP/1.1" 200 -]
[2025-08-01 10:28:03,422: INFO: _internal: 127.0.0.1 - - [01/Aug/2025 10:28:03] "GET / HTTP/1.1" 200 -]
